version: "3.8"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass123
  app:
    build: .
    command: > 
      sh -c "python manage.py wait_for_db && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=testpass123
    depends_on:
      - db
